version: "3.8"

services:
  audio_book_api:
    build:
      context: ../audio_book_api
      dockerfile: ../docker/audio_book.Dockerfile
    container_name: audio-api
    volumes:
      - "../audio_book_api/src:/app/src"
    ports:
      - "8080:8080"
    networks:
      - books_private

  # audio_note:
  #   build:
  #     context: ../audio_note
  #     dockerfile: ../docker/audio_note.Dockerfile
  #   container_name: audio-note
  #   volumes:
  #     - "../audio_note:/app"
  #   ports:
  #     - "8000:8000"
  #   networks:
  #     - notes_private

  postgres_db:
    container_name: audio-postgres
    image: "postgres:16"
    restart: always
    env_file: "../.env.postgres"
    volumes:
      - audio_postgres:/var/lib/postgresql/data/
    networks:
      - notes_private
    ports:
      - "5432:5432"

  mongo_db:
    container_name: audio-mongo
    image: "mongodb/mongodb-community-server:7.0.0-ubuntu2204"
    restart: always
    networks:
      - books_private
    ports:
      - "27017:27017"

volumes:
  audio_postgres:

networks:
  common:
    driver: bridge
  notes_private:
    driver: bridge
  books_private:
    driver: bridge
